[package]
name        = "extabs"
version     = "0.1.0"
edition     = "2021"
description = "Implements expandtabs for String"
author      = "Miasnenko Dmitry <clowzed.work@gmail.com>"
license     = "MIT"

[dependencies]