[package]
name        = "extabs"
version     = "1.0.3"
edition     = "2021"
description = "Implements expandtabs for String"
author      = "Miasnenko Dmitry <clowzed.work@gmail.com>"
license     = "MIT"
repository = "https://github.com/clowzed/extabs.git"

[dependencies]